name: "Build and test wrapper"
on: # rebuild any branch changes

  pull_request:
  push:
    branches:
      - '*'
      - '!auto/build-dist'
    tags-ignore:
      - '*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run pack
    - run: npm run test
    - run: |
        cat > test.go <<EOF
        package main

        import "fmt"

        func main() {
          fmt.Println("hello go action!")
        }
        EOF
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist/index.js
          action.yml
    - uses: actions/upload-artifact@v2
      with:
        name: test
        path: |
          test.go
  test:
    strategy:
      matrix:
        runs-on: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.runs-on }}
    needs: build
    steps:
    - name: Download assets
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Download test
      uses: actions/download-artifact@v2
      with:
        name: test
    - uses: actions/setup-go@v1
    - if: ${{ runner.os == 'Linux' }}
      run: |
        go build -o dist/main_linux test.go
    - if: ${{ runner.os == 'Windows' }}
      run: |
        go build -o dist/main_windows.exe test.go
    - if: ${{ runner.os == 'macOS' }}
      run: |
        go build -o dist/main_darwin test.go
    - uses: ./

  publish: # Publish the freshly built package
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/test' && github.event_name == 'push'  }}
    steps:
    - uses: actions/checkout@v2
    - name: Download assets
      uses: actions/download-artifact@v2
      with:
        name: dist
    - uses: actions-go/push@v1
      with:
        commit-message: '[Auto] update packaged index.js'
        force: true
        remote-ref: refs/heads/auto/build-dist
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
