name: "build-dist"
on: # rebuild any branch changes
  push:
    paths:
      - '*'
      - '**/*'
      - '!dist/**'
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run pack
    - uses: actions-go/push@v1
      with:
        commit-message: '[Auto] update packaged index.js'
