name: "build-dist"
on: # rebuild any branch changes
  push:
    paths:
      - '*'
      - '**/*'
      - '!dist/**'
    tags-ignore:
      - '*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run pack

    - uses: actions/upload-artifact@v2
      with:
        name: dist/index.js
        path: dist/index.js
    - uses: actions/upload-artifact@v2
      with:
        name: action.yml
        path: action.yml
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello world

    # - uses: actions-go/push@v1
    #   if: ${{ github.ref == "refs/heads/master" }}
    #   with:
    #     commit-message: '[Auto] update packaged index.js'
    #     force: true
    #     remote-ref: refs/heads/auto/build-dist
