name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

  build: # make sure build/ci work properly
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.9.3' # The Go version to download (if necessary) and use.
    - run: |
        npm install
        npm run all
        npm run pack
    - if: ${{ runner.os == 'Linux' }}
      run: |
        go build -o dist/main_linux test/main.go
    - if: ${{ runner.os == 'Windows' }}
      run: |
        go build -o dist/main_windows.exe test/main.go
    - if: ${{ runner.os == 'macOS' }}
      run: |
        go build -o dist/main_darwin test/main.go
    - uses: ./
